### ISSUE TITLE
libgl: undefined reference errors when trying to compile on Linux Mint 20.1

### ISSUE THREAD

**Issue by mrgw454** [jmthompson/xgs#3]
Hello,

I'm able to successfully compile xgs on my "Buster" based Raspberry Pi, but unable to get it compile on my Linux Mint 20.1 system.

```
Scanning dependencies of target xgs
[ 97%] Building CXX object CMakeFiles/xgs.dir/emulator/main.cc.o
[100%] Linking CXX executable xgs
/usr/bin/ld: gl/libgl.a(gl.c.o): in function `_impl_glIsVertexArray':
gl.c:(.text+0x17): undefined reference to `glXGetProcAddressARB'
/usr/bin/ld: gl/libgl.a(gl.c.o): in function `_impl_glBindVertexArray':
gl.c:(.text+0x49): undefined reference to `glXGetProcAddressARB'
/usr/bin/ld: gl/libgl.a(gl.c.o): in function `_impl_glFlushMappedBufferRange':
gl.c:(.text+0x84): undefined reference to `glXGetProcAddressARB'
/usr/bin/ld: gl/libgl.a(gl.c.o): in function `_impl_glRenderbufferStorageMultisample':
gl.c:(.text+0xd0): undefined reference to `glXGetProcAddressARB'
/usr/bin/ld: gl/libgl.a(gl.c.o): in function `_impl_glGenerateMipmap':
gl.c:(.text+0x113): undefined reference to `glXGetProcAddressARB'
/usr/bin/ld: gl/libgl.a(gl.c.o):gl.c:(.text+0x157): more undefined references to `glXGetProcAddressARB' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/xgs.dir/build.make:100: xgs] Error 1
make[1]: *** [CMakeFiles/Makefile2:316: CMakeFiles/xgs.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```
Not sure if this is because of an incompatible GL library.  Thanks for any assistance you can provide!

**Comment by jmthompson** [comment]
Hello! Sorry for the delay, been massively busy at work lately. My guess is
that the file gl/gl.c that's included in the repo right now may not be
quite correct for your system. On line 92 in that file is the call to this
function; try changing it to just use "glXGetProcAddress" (iow remove the
"ARB") and see if rebuilding from there helps.

BTW I'm a bit surprised someone is still trying to use XGS :)

**Comment by mrgw454** [comment]
Hi Joshua - no problem on the delay, sir.  This is just hobby stuff.  :)

I did look for line 92 in the file you specify, but I see this:

```
ron@x570:~/source/xgs/gl$ ls -l
total 340
-rw-rw-r-- 1 ron ron    160 Oct  7 17:46 CMakeLists.txt
-rw-rw-r-- 1 ron ron 183086 Oct 12 08:52 gl.c
-rw-rw-r-- 1 ron ron 156102 Oct  7 17:46 gl.h
ron@x570:~/source/xgs/gl$ sed '92!d' gl.c
  _glptr_glGenerateMipmap = (PFN_glGenerateMipmap)GalogenGetProcAddress("glGenerateMipmap");

```
In the source I pulled from git, it looks like this would be on line 62:

`#define GalogenGetProcAddress(name) (*glXGetProcAddressARB)((const GLubyte*)name)`

If I remove the "ARB" part and try to compile, I get this:

```
[ 97%] Building CXX object CMakeFiles/xgs.dir/emulator/main.cc.o
[100%] Linking CXX executable xgs
/usr/bin/ld: gl/libgl.a(gl.c.o): in function `_impl_glIsVertexArray':
gl.c:(.text+0x17): undefined reference to `glXGetProcAddress'
/usr/bin/ld: gl/libgl.a(gl.c.o): in function `_impl_glBindVertexArray':
gl.c:(.text+0x49): undefined reference to `glXGetProcAddress'
/usr/bin/ld: gl/libgl.a(gl.c.o): in function `_impl_glFlushMappedBufferRange':
gl.c:(.text+0x84): undefined reference to `glXGetProcAddress'
/usr/bin/ld: gl/libgl.a(gl.c.o): in function `_impl_glRenderbufferStorageMultisample':
gl.c:(.text+0xd0): undefined reference to `glXGetProcAddress'
/usr/bin/ld: gl/libgl.a(gl.c.o): in function `_impl_glGenerateMipmap':
gl.c:(.text+0x113): undefined reference to `glXGetProcAddress'
/usr/bin/ld: gl/libgl.a(gl.c.o):gl.c:(.text+0x157): more undefined references to `glXGetProcAddress' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/xgs.dir/build.make:100: xgs] Error 1
make[1]: *** [CMakeFiles/Makefile2:316: CMakeFiles/xgs.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```

As for wanting to try xgs, I thought it was an interesting project and noticed you had it working for the Raspberry Pi (which is what I was looking for) but thought it would be nice to have it running on my main Linux workstation as well.

Thanks again for all your help!

-Ron
